style: normalize indentation to 4 spaces in shell scripts

diff --git a/.local/bin/wifi-connect b/.local/bin/wifi-connect
--- a/.local/bin/wifi-connect
+++ b/.local/bin/wifi-connect
@@ -4,12 +4,17 @@ SSID="$1"
 
 # Check if SSID argument is provided
 if [ -z "$SSID" ]; then
-  echo "Error: No SSID provided."
-  exit 1
+    nmcli device wifi list
+
+    read -r -p "Enter SSID: " SSID
+    if [ -z "$SSID" ]; then
+        echo "Error: No SSID provided."
+        exit 1
+    fi
 fi
 
 # Connect to Wi-Fi using nmcli
 if ! nmcli --ask device wifi connect "$SSID"; then
-  echo "Error: Failed to connect to Wi-Fi network '$SSID'."
-  exit 1
+    echo "Error: Failed to connect to Wi-Fi network '$SSID'."
+    exit 1
 fi
diff --git a/.local/bin/xwcopy b/.local/bin/xwcopy
--- a/.local/bin/xwcopy
+++ b/.local/bin/xwcopy
@@ -7,15 +7,15 @@ DE=$(get_desktop_environment)
 is_desktop_environment_supported "$DE"
 
 if [[ "$DE" == "i3" ]]; then
-  COPY_CMD="xclip -selection clipboard"
+    COPY_CMD="xclip -selection clipboard"
 elif [[ "$DE" == "sway" ]]; then
-  COPY_CMD="wl-copy"
+    COPY_CMD="wl-copy"
 fi
 
 # Vérifier si stdin contient des données
 if [ -t 0 ]; then
-  echo "Error: No input detected. Please provide text via stdin."
-  exit 1
+    echo "Error: No input detected. Please provide text via stdin."
+    exit 1
 fi
 
 cat | $COPY_CMD
