refactor: add logging and desktop environment utilities
- Add new library modules for logging and DE detection
- Refactor scripts to use new log.sh helper functions
- Refactor scripts to use new de.sh for desktop environment detection

diff --git a/.local/sbin/local-net b/.local/sbin/local-net
--- a/.local/sbin/local-net
+++ b/.local/sbin/local-net
@@ -1,56 +1,66 @@
 #!/usr/bin/env bash
+set -euo pipefail
 
-DNS_IP="1.1.1.1"
-DOCKER_API_VERSION="1.41"
-
-DATA_DIR="${HOME}/Data/adguardhome"
-CONFIG_FILE_PATH="${HOME}/.config/local/net.json"
+NET_CONFIG_FILE_PATH="${HOME}/.config/local/net.json"
+INFRA_CONFIG_FILE_PATH="${HOME}/.config/local/infra.json"
 
 CONTAINER_NAME="local-net"
+DATA_DIR="${HOME}/Data/adguardhome"
+LOCAL_NET_VERSION="$(jq -r '.versions.local_net' "$INFRA_CONFIG_FILE_PATH")"
+DOCKER_API_VERSION="$(jq -r '.versions.docker_api' "$INFRA_CONFIG_FILE_PATH")"
+DNS_IP="1.1.1.1"
+
+command_exists() {
+  if ! command -v "$1" >/dev/null; then
+    log error "The command '${1}' is missing. Please install it."
+    exit 1
+  fi
+}
 
 
-if ! command -v jq &>/dev/null; then
-  echo "Error: jq is not installed."
-  exit 1
-fi
+for cmd in docker jq sudo; do
+  command_exists "$cmd"
+done
 
 # Start local-net
-if [ ! -f "$CONFIG_FILE_PATH" ]; then
+if [ ! -f "$NET_CONFIG_FILE_PATH" ]; then
   echo "Error: config file does not exist."
   exit 1
 fi
 
 mkdir -p "$DATA_DIR"/{work,conf}
 
-if [ "$(docker container ls --filter "name=${CONTAINER_NAME}" --quiet | wc -l)" -eq 0 ]; then
-  echo -e "Running container ${CONTAINER_NAME}"
-
-  if [ "$(grep -c "ID=nixos" /etc/os-release)" -eq 0 ]; then
-    # Configure resolv.conf
-    LOCAL_IP_DNS="$(jq -r '.ip_addresses.dns.ip_address' "$CONFIG_FILE_PATH")"
-
-    if ! grep "$LOCAL_IP_DNS" /etc/systemd/resolved.conf > /dev/null ; then
-      sudo sed -i -e 's/#DNSStubListener=yes/DNSStubListener=no/' -e "s/#DNS=/DNS=${LOCAL_IP_DNS}/" /etc/systemd/resolved.conf
-
-      sudo systemctl restart systemd-resolved
-    fi
-  fi
-
-  exec docker container run \
-    -t \
-    --rm \
-    --mount type=bind,src=/var/run/dbus,dst=/var/run/dbus \
-    --mount type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock \
-    --mount type=bind,src=${CONFIG_FILE_PATH},dst=/tmp/local-net.json \
-    --mount type=bind,src=${DATA_DIR}/work,dst=/opt/adguardhome/work \
-    --mount type=bind,src=${DATA_DIR}/conf,dst=/opt/adguardhome/conf \
-    --net host \
-    --dns "$DNS_IP" \
-    --security-opt seccomp=unconfined \
-    --security-opt apparmor=unconfined \
-    --cap-add=NET_ADMIN \
-    --env DOCKER_API_VERSION=$DOCKER_API_VERSION \
-    --name "$CONTAINER_NAME" \
-    juli3nk/local-net \
-      -debug
+# If container already exists, just start it
+if docker container inspect "$CONTAINER_NAME" &>/dev/null; then
+  echo "Container $CONTAINER_NAME already exists. Starting it..."
+  # docker container start -a "$CONTAINER_NAME"
+  docker container rm "$CONTAINER_NAME"
+  exit $?
 fi
+
+echo -e "Running container ${CONTAINER_NAME}"
+
+# Optional: resolv.conf tweaks (if not on NixOS)
+if [ "$(grep -c "ID=nixos" /etc/os-release)" -eq 0 ]; then
+  LOCAL_IP_DNS="$(jq -r '.ip_addresses.dns.ip_address' "$NET_CONFIG_FILE_PATH")"
+
+  if ! grep "$LOCAL_IP_DNS" /etc/systemd/resolved.conf > /dev/null ; then
+    sudo sed -i -e 's/#DNSStubListener=yes/DNSStubListener=no/' -e "s/#DNS=/DNS=${LOCAL_IP_DNS}/" /etc/systemd/resolved.conf
+    sudo systemctl restart systemd-resolved
+  fi
+fi
+
+exec docker container run \
+  -t \
+  --mount type=bind,src=/var/run/dbus,dst=/var/run/dbus \
+  --mount type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock \
+  --mount type=bind,src=${NET_CONFIG_FILE_PATH},dst=/tmp/local-net.json,ro \
+  --network host \
+  --dns "$DNS_IP" \
+  --security-opt seccomp=unconfined \
+  --security-opt apparmor=unconfined \
+  --cap-add=NET_ADMIN \
+  --env DOCKER_API_VERSION=$DOCKER_API_VERSION \
+  --name "$CONTAINER_NAME" \
+  "juli3nk/local-net:${LOCAL_NET_VERSION}" \
+    -debug
